# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContourFilterUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1482, 636)
        Dialog.setAutoFillBackground(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_11.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_11)
        self.doubleSpinBox_L11 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L11.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L11.setMaximum(999999999.0)
        self.doubleSpinBox_L11.setObjectName("doubleSpinBox_L11")
        self.horizontalLayout.addWidget(self.doubleSpinBox_L11)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(6, 16))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.doubleSpinBox_H11 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H11.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H11.setMaximum(9999999.0)
        self.doubleSpinBox_H11.setProperty("value", 99999.0)
        self.doubleSpinBox_H11.setObjectName("doubleSpinBox_H11")
        self.horizontalLayout.addWidget(self.doubleSpinBox_H11)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_12.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_12)
        self.doubleSpinBox_L12 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L12.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L12.setMaximum(999999999.0)
        self.doubleSpinBox_L12.setObjectName("doubleSpinBox_L12")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_L12)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMaximumSize(QtCore.QSize(6, 16))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.doubleSpinBox_H12 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H12.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H12.setMaximum(9999999.0)
        self.doubleSpinBox_H12.setProperty("value", 99999.0)
        self.doubleSpinBox_H12.setObjectName("doubleSpinBox_H12")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_H12)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_13.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_13)
        self.doubleSpinBox_L13 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L13.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L13.setMinimum(-90.0)
        self.doubleSpinBox_L13.setMaximum(999999999.0)
        self.doubleSpinBox_L13.setSingleStep(1.0)
        self.doubleSpinBox_L13.setObjectName("doubleSpinBox_L13")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_L13)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setMaximumSize(QtCore.QSize(6, 16))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.doubleSpinBox_H13 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H13.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H13.setMaximum(9999999.0)
        self.doubleSpinBox_H13.setProperty("value", 99999.0)
        self.doubleSpinBox_H13.setObjectName("doubleSpinBox_H13")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_H13)
        self.gridLayout.addLayout(self.horizontalLayout_16, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_21 = QtWidgets.QComboBox(Dialog)
        self.comboBox_21.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_21.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_21)
        self.doubleSpinBox_L21 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L21.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L21.setMaximum(999999999.0)
        self.doubleSpinBox_L21.setObjectName("doubleSpinBox_L21")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_L21)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(6, 16))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.doubleSpinBox_H21 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H21.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H21.setMaximum(9999999.0)
        self.doubleSpinBox_H21.setProperty("value", 99999.0)
        self.doubleSpinBox_H21.setObjectName("doubleSpinBox_H21")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_H21)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_22 = QtWidgets.QComboBox(Dialog)
        self.comboBox_22.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_22.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_22)
        self.doubleSpinBox_L22 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L22.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L22.setMaximum(999999999.0)
        self.doubleSpinBox_L22.setObjectName("doubleSpinBox_L22")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_L22)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMaximumSize(QtCore.QSize(6, 16))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.doubleSpinBox_H22 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H22.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H22.setMaximum(9999999.0)
        self.doubleSpinBox_H22.setProperty("value", 99999.0)
        self.doubleSpinBox_H22.setObjectName("doubleSpinBox_H22")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_H22)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(8)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox_23 = QtWidgets.QComboBox(Dialog)
        self.comboBox_23.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_23.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_23)
        self.doubleSpinBox_L23 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L23.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L23.setMaximum(999999999.0)
        self.doubleSpinBox_L23.setObjectName("doubleSpinBox_L23")
        self.horizontalLayout_18.addWidget(self.doubleSpinBox_L23)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setMaximumSize(QtCore.QSize(6, 16))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.doubleSpinBox_H23 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H23.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H23.setMaximum(9999999.0)
        self.doubleSpinBox_H23.setProperty("value", 99999.0)
        self.doubleSpinBox_H23.setObjectName("doubleSpinBox_H23")
        self.horizontalLayout_18.addWidget(self.doubleSpinBox_H23)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_31 = QtWidgets.QComboBox(Dialog)
        self.comboBox_31.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_31.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_31)
        self.doubleSpinBox_L31 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L31.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L31.setMaximum(999999999.0)
        self.doubleSpinBox_L31.setObjectName("doubleSpinBox_L31")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_L31)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMaximumSize(QtCore.QSize(6, 16))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.doubleSpinBox_H31 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H31.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H31.setMaximum(9999999.0)
        self.doubleSpinBox_H31.setProperty("value", 99999.0)
        self.doubleSpinBox_H31.setObjectName("doubleSpinBox_H31")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_H31)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox_32 = QtWidgets.QComboBox(Dialog)
        self.comboBox_32.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_32.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_32.setObjectName("comboBox_32")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_32)
        self.doubleSpinBox_L32 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L32.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L32.setMaximum(999999999.0)
        self.doubleSpinBox_L32.setObjectName("doubleSpinBox_L32")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_L32)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMaximumSize(QtCore.QSize(6, 16))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.doubleSpinBox_H32 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H32.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H32.setMaximum(9999999.0)
        self.doubleSpinBox_H32.setProperty("value", 99999.0)
        self.doubleSpinBox_H32.setObjectName("doubleSpinBox_H32")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_H32)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(8)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.comboBox_33 = QtWidgets.QComboBox(Dialog)
        self.comboBox_33.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_33.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_33)
        self.doubleSpinBox_L33 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L33.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L33.setMaximum(999999999.0)
        self.doubleSpinBox_L33.setObjectName("doubleSpinBox_L33")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_L33)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setMaximumSize(QtCore.QSize(6, 16))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        self.doubleSpinBox_H33 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H33.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H33.setMaximum(9999999.0)
        self.doubleSpinBox_H33.setProperty("value", 99999.0)
        self.doubleSpinBox_H33.setObjectName("doubleSpinBox_H33")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_H33)
        self.gridLayout.addLayout(self.horizontalLayout_20, 2, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_41 = QtWidgets.QComboBox(Dialog)
        self.comboBox_41.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_41.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_41.setObjectName("comboBox_41")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_41)
        self.doubleSpinBox_L41 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L41.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L41.setMaximum(999999999.0)
        self.doubleSpinBox_L41.setObjectName("doubleSpinBox_L41")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_L41)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(6, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.doubleSpinBox_H41 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H41.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H41.setMaximum(9999999.0)
        self.doubleSpinBox_H41.setProperty("value", 99999.0)
        self.doubleSpinBox_H41.setObjectName("doubleSpinBox_H41")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_H41)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBox_42 = QtWidgets.QComboBox(Dialog)
        self.comboBox_42.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_42.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_42.setObjectName("comboBox_42")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.comboBox_42.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_42)
        self.doubleSpinBox_L42 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L42.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L42.setMaximum(999999999.0)
        self.doubleSpinBox_L42.setObjectName("doubleSpinBox_L42")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_L42)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(6, 16))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.doubleSpinBox_H42 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H42.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H42.setMaximum(9999999.0)
        self.doubleSpinBox_H42.setProperty("value", 99999.0)
        self.doubleSpinBox_H42.setObjectName("doubleSpinBox_H42")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_H42)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.comboBox_43 = QtWidgets.QComboBox(Dialog)
        self.comboBox_43.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_43.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_43.setObjectName("comboBox_43")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_43)
        self.doubleSpinBox_L43 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L43.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L43.setMaximum(999999999.0)
        self.doubleSpinBox_L43.setObjectName("doubleSpinBox_L43")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_L43)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setMaximumSize(QtCore.QSize(6, 16))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.doubleSpinBox_H43 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H43.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H43.setMaximum(9999999.0)
        self.doubleSpinBox_H43.setProperty("value", 99999.0)
        self.doubleSpinBox_H43.setObjectName("doubleSpinBox_H43")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_H43)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.comboBox_51 = QtWidgets.QComboBox(Dialog)
        self.comboBox_51.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_51.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_51.setObjectName("comboBox_51")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.comboBox_51.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_51)
        self.doubleSpinBox_L51 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L51.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L51.setMaximum(999999999.0)
        self.doubleSpinBox_L51.setObjectName("doubleSpinBox_L51")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_L51)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMaximumSize(QtCore.QSize(6, 16))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.doubleSpinBox_H51 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H51.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H51.setMaximum(9999999.0)
        self.doubleSpinBox_H51.setProperty("value", 99999.0)
        self.doubleSpinBox_H51.setObjectName("doubleSpinBox_H51")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_H51)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBox_52 = QtWidgets.QComboBox(Dialog)
        self.comboBox_52.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_52.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_52.setObjectName("comboBox_52")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.comboBox_52.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_52)
        self.doubleSpinBox_L52 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L52.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L52.setMaximum(999999999.0)
        self.doubleSpinBox_L52.setObjectName("doubleSpinBox_L52")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_L52)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMaximumSize(QtCore.QSize(6, 16))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.doubleSpinBox_H52 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H52.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H52.setMaximum(9999999.0)
        self.doubleSpinBox_H52.setProperty("value", 99999.0)
        self.doubleSpinBox_H52.setObjectName("doubleSpinBox_H52")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_H52)
        self.gridLayout.addLayout(self.horizontalLayout_11, 4, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(8)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comboBox_53 = QtWidgets.QComboBox(Dialog)
        self.comboBox_53.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_53.setMaximumSize(QtCore.QSize(69, 20))
        self.comboBox_53.setObjectName("comboBox_53")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.comboBox_53.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_53)
        self.doubleSpinBox_L53 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_L53.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_L53.setMaximum(999999999.0)
        self.doubleSpinBox_L53.setObjectName("doubleSpinBox_L53")
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_L53)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setMaximumSize(QtCore.QSize(6, 16))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.doubleSpinBox_H53 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_H53.setMaximumSize(QtCore.QSize(50, 20))
        self.doubleSpinBox_H53.setMaximum(9999999.0)
        self.doubleSpinBox_H53.setProperty("value", 99999.0)
        self.doubleSpinBox_H53.setObjectName("doubleSpinBox_H53")
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_H53)
        self.gridLayout.addLayout(self.horizontalLayout_14, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(600, 616))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 600, 571))
        self.tableWidget.setMinimumSize(QtCore.QSize(431, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(600, 16777215))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(15)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(340, 580, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox_hole = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hole.setGeometry(QtCore.QRect(20, 580, 121, 21))
        self.checkBox_hole.setChecked(False)
        self.checkBox_hole.setObjectName("checkBox_hole")
        self.checkBox_lane = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_lane.setGeometry(QtCore.QRect(150, 580, 131, 21))
        self.checkBox_lane.setChecked(False)
        self.checkBox_lane.setObjectName("checkBox_lane")
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox_11.setItemText(0, _translate("Dialog", "area"))
        self.comboBox_11.setItemText(1, _translate("Dialog", "Eccentricity"))
        self.comboBox_11.setItemText(2, _translate("Dialog", "EquivDiameter"))
        self.comboBox_11.setItemText(3, _translate("Dialog", "Extent"))
        self.comboBox_11.setItemText(4, _translate("Dialog", "Orientation"))
        self.comboBox_11.setItemText(5, _translate("Dialog", "solidity"))
        self.comboBox_11.setItemText(6, _translate("Dialog", "rect_w"))
        self.comboBox_11.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_3.setText(_translate("Dialog", "-"))
        self.comboBox_12.setItemText(0, _translate("Dialog", "Eccentricity"))
        self.comboBox_12.setItemText(1, _translate("Dialog", "rect_w"))
        self.comboBox_12.setItemText(2, _translate("Dialog", "area"))
        self.comboBox_12.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_12.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_12.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_12.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_12.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_7.setText(_translate("Dialog", "-"))
        self.comboBox_13.setItemText(0, _translate("Dialog", "Orientation"))
        self.comboBox_13.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_13.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_13.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_13.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_13.setItemText(5, _translate("Dialog", "solidity"))
        self.comboBox_13.setItemText(6, _translate("Dialog", "rect_w"))
        self.comboBox_13.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_17.setText(_translate("Dialog", "-"))
        self.comboBox_21.setItemText(0, _translate("Dialog", "rect_w"))
        self.comboBox_21.setItemText(1, _translate("Dialog", "Eccentricity"))
        self.comboBox_21.setItemText(2, _translate("Dialog", "area"))
        self.comboBox_21.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_21.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_21.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_21.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_21.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_4.setText(_translate("Dialog", "-"))
        self.comboBox_22.setItemText(0, _translate("Dialog", "rect_h"))
        self.comboBox_22.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_22.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_22.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_22.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_22.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_22.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_22.setItemText(7, _translate("Dialog", "rect_w"))
        self.label_8.setText(_translate("Dialog", "-"))
        self.comboBox_23.setItemText(0, _translate("Dialog", "EquivDiameter"))
        self.comboBox_23.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_23.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_23.setItemText(3, _translate("Dialog", "Extent"))
        self.comboBox_23.setItemText(4, _translate("Dialog", "Orientation"))
        self.comboBox_23.setItemText(5, _translate("Dialog", "solidity"))
        self.comboBox_23.setItemText(6, _translate("Dialog", "rect_w"))
        self.comboBox_23.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_19.setText(_translate("Dialog", "-"))
        self.comboBox_31.setItemText(0, _translate("Dialog", "Extent"))
        self.comboBox_31.setItemText(1, _translate("Dialog", "Orientation"))
        self.comboBox_31.setItemText(2, _translate("Dialog", "area"))
        self.comboBox_31.setItemText(3, _translate("Dialog", "Eccentricity"))
        self.comboBox_31.setItemText(4, _translate("Dialog", "EquivDiameter"))
        self.comboBox_31.setItemText(5, _translate("Dialog", "solidity"))
        self.comboBox_31.setItemText(6, _translate("Dialog", "rect_w"))
        self.comboBox_31.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_5.setText(_translate("Dialog", "-"))
        self.comboBox_32.setItemText(0, _translate("Dialog", "solidity"))
        self.comboBox_32.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_32.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_32.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_32.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_32.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_32.setItemText(6, _translate("Dialog", "rect_w"))
        self.comboBox_32.setItemText(7, _translate("Dialog", "rect_h"))
        self.label_9.setText(_translate("Dialog", "-"))
        self.comboBox_33.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_33.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_33.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_33.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_33.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_33.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_33.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_33.setItemText(7, _translate("Dialog", "rect_w"))
        self.comboBox_33.setItemText(8, _translate("Dialog", "rect_h"))
        self.label_21.setText(_translate("Dialog", "-"))
        self.comboBox_41.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_41.setItemText(1, _translate("Dialog", "rect_w"))
        self.comboBox_41.setItemText(2, _translate("Dialog", "Extent"))
        self.comboBox_41.setItemText(3, _translate("Dialog", "area"))
        self.comboBox_41.setItemText(4, _translate("Dialog", "Eccentricity"))
        self.comboBox_41.setItemText(5, _translate("Dialog", "EquivDiameter"))
        self.comboBox_41.setItemText(6, _translate("Dialog", "Orientation"))
        self.comboBox_41.setItemText(7, _translate("Dialog", "solidity"))
        self.comboBox_41.setItemText(8, _translate("Dialog", "rect_h"))
        self.label_6.setText(_translate("Dialog", "-"))
        self.comboBox_42.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_42.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_42.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_42.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_42.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_42.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_42.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_42.setItemText(7, _translate("Dialog", "rect_w"))
        self.comboBox_42.setItemText(8, _translate("Dialog", "rect_h"))
        self.label_10.setText(_translate("Dialog", "-"))
        self.comboBox_43.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_43.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_43.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_43.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_43.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_43.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_43.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_43.setItemText(7, _translate("Dialog", "rect_w"))
        self.comboBox_43.setItemText(8, _translate("Dialog", "rect_h"))
        self.label_13.setText(_translate("Dialog", "-"))
        self.comboBox_51.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_51.setItemText(1, _translate("Dialog", "rect_h"))
        self.comboBox_51.setItemText(2, _translate("Dialog", "area"))
        self.comboBox_51.setItemText(3, _translate("Dialog", "Eccentricity"))
        self.comboBox_51.setItemText(4, _translate("Dialog", "EquivDiameter"))
        self.comboBox_51.setItemText(5, _translate("Dialog", "Extent"))
        self.comboBox_51.setItemText(6, _translate("Dialog", "Orientation"))
        self.comboBox_51.setItemText(7, _translate("Dialog", "solidity"))
        self.comboBox_51.setItemText(8, _translate("Dialog", "rect_w"))
        self.label_11.setText(_translate("Dialog", "-"))
        self.comboBox_52.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_52.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_52.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_52.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_52.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_52.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_52.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_52.setItemText(7, _translate("Dialog", "rect_w"))
        self.comboBox_52.setItemText(8, _translate("Dialog", "rect_h"))
        self.label_12.setText(_translate("Dialog", "-"))
        self.comboBox_53.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_53.setItemText(1, _translate("Dialog", "area"))
        self.comboBox_53.setItemText(2, _translate("Dialog", "Eccentricity"))
        self.comboBox_53.setItemText(3, _translate("Dialog", "EquivDiameter"))
        self.comboBox_53.setItemText(4, _translate("Dialog", "Extent"))
        self.comboBox_53.setItemText(5, _translate("Dialog", "Orientation"))
        self.comboBox_53.setItemText(6, _translate("Dialog", "solidity"))
        self.comboBox_53.setItemText(7, _translate("Dialog", "rect_w"))
        self.comboBox_53.setItemText(8, _translate("Dialog", "rect_h"))
        self.label_15.setText(_translate("Dialog", "-"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "area"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "center"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Eccentricity"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "EquivDiameter"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Extent"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Orientation"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "solidity"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "rect_x"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "rect_y"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "rect_w"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "rect_h"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "L"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "R"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "T"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Dialog", "B"))
        self.checkBox_hole.setText(_translate("Dialog", "fill hole"))
        self.checkBox_lane.setText(_translate("Dialog", "erase lane"))

